"""Read public LOL exports; retain only compact, auditable research evidence.

This is NOT an installer or a measure of mod quality/popularity. Folder-name
matches require human review: a patch or disabled option is not a main mod.
No complete exports or downloaded mod assets are persisted.
"""
from __future__ import annotations

import argparse
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import re
import urllib.request


SLUGS = (
    "lorerim", "nordic-souls", "gts", "nolvus-awakening",
    "wunduniik-chapter-v", "apostasy", "anvil", "csvo", "septimus",
    "tuxborn", "elderteej", "eldergleam-a-next-gen-modlist-4-0-2",
    "mages-vikings", "kirbykings-modlist-3", "invicta-12",
    "vagabond-remastered", "ngvo", "tempus-maledictum",
    "winds-of-the-north", "wildlander",
)
PATTERNS = {
    "mesh": r"high[ -]?poly project|(?<![\w.])HPP\b|mesh improvement compilation|\bMIC(?= -|$)|garlic - a garlic|less poly coal",
    "books": r"book[ -]?covers? skyrim|\bBCS\b|better books and letters|book covers|\blost library\b|\brustic books\b|legacy of the dragonborn|legacyofthedragonborn|\bLOTD\b",
    "crafting": r"ars metallica|complete crafting|\bCCOR\b|crafting recipe distributor|smelting plus|simple smithing overhaul|smithing perks overhaul|smithing experience overhaul",
    "animation": r"animation queue fix|\bAQF\b",
    "horses": r"convenient horses|immersive horses|simplest horses|simple horse se|press h|a horse.s life|followers ride horses|nethers follower framework|nether.s follower framework|simple follower framework",
}

MAIN_NAMES = {
    "HPP": {"high poly project"},
    "MIC": {"mesh improvement compilation"},
    "BCS": {"book covers skyrim", "book covers skyrim updated"},
    "Ars": {"ars metallica", "ars metallica - smithing enhancement"},
    "CCOR": {"complete crafting overhaul remastered"},
    "CRD": {"crafting recipe distributor"},
    "AQF": {"animation queue fix"},
    "CH": {"convenient horses"},
    "SH": {"simplest horses", "simplest horses (and other mounts)"},
    "IH": {"immersive horses"},
    "Press H": {"press h to horse"},
    "AHL": {"a horse's life"},
    "LOTD": {"legacy of the dragonborn", "legacy of the dragonborn sse", "legacy of the dragonborn v6"},
}


def normalize_folder(text: str) -> str:
    value = text.strip().lstrip("+-*").strip().lower()
    value = re.sub(r"^\d+\s+", "", value)  # Kirbyking's numbered labels
    return re.sub(r"\s+\d{3,}$", "", value)


def main_mods(export: dict) -> dict[str, list[dict]]:
    accepted = {key: [] for key in MAIN_NAMES}
    for row in export.get("matches", []):
        if row["file"] != "modlist.txt" or row["state"] != "enabled":
            continue
        normalized = normalize_folder(row["text"])
        for key, aliases in MAIN_NAMES.items():
            if normalized in aliases:
                accepted[key].append(row)
    return accepted


def census_markdown(document: dict) -> str:
    included, excluded = [], []
    for item in document["exports"]:
        if "error" in item:
            excluded.append((item, item["error"]))
        elif not any(f["file"] == "modlist.txt" for f in item["files"]):
            excluded.append((item, "plugin/load-order only; cannot count mesh/DLL absence"))
        elif (item.get("updated") or "")[:10] < "2025-01-01":
            excluded.append((item, "pre-2025 export; historical supplement only"))
        else:
            included.append(item)
    keys = list(MAIN_NAMES)
    lines = [f"# Requested-slot export census - {document['retrieved_utc'][:10]}", "",
             f"Retrieved UTC: {document['retrieved_utc']}. Generated by `audit/survey_requested_slots.py`.", "",
             "## Method", "",
             "Convenience sample selected from the existing ecosystem survey, not a ranked or representative sample of all modlists. One export per list. The API's updated date is the export date, not necessarily the release date or proof of current support. Author-verified releases and third-party mirrors are not interchangeable. Nolvus/Wunduniik exports in particular must not be read as official release manifests. Related list families are not statistically independent.", "",
             "Only exports dated 2025 or later with an available MO2 modlist.txt enter the denominator. Presence and valid text are checked, not export completeness. Count only enabled (+) exact main-folder matches under the aliases below, with numbered prefixes/Nexus-ID suffixes normalized. No patch-only mentions, disabled (-) options, unmanaged (*) rows, or plugins-only inference. A dash means no recognized enabled main folder in this export, NOT proof no bundled/renamed assets exist or that the mod is unsuitable. Main folders do not prove which files win, FOMOD choices, exact installed version, or runtime compatibility.", "",
             "BCS includes original and 'Book Covers Skyrim Updated' folder families, not PBR/patch/Lost Library-only entries; exact route requires package inspection. Legacy of the Dragonborn bundles BCS, so standalone-folder counts understate book-cover coverage; LOTD is not automatically counted as a separately installed BCS package. HPP and MIC can coexist. CRD is recipe tooling, not a full replacement for Ars/CCOR. Horse follower frameworks are not counted as player horse overhauls.", "",
             "## Main matrix", "",
             "| Export (version) | Export date | " + " | ".join(keys) + " |",
             "|---|---|" + "---|" * len(keys)]
    counts = {key: 0 for key in keys}
    recent_counts = {key: 0 for key in keys}
    recent_n = 0
    for item in included:
        found = main_mods(item)
        recent = item["updated"][:4] == "2026"
        recent_n += int(recent)
        for key in keys:
            counts[key] += int(bool(found[key]))
            recent_counts[key] += int(recent and bool(found[key]))
        lines.append(f"| [{item['name']}]({item['page']}) ({item.get('version') or 'unversioned'}) | {item['updated'][:10]} | " + " | ".join("Yes" if found[key] else "—" for key in keys) + " |")
    lines.extend(["| **Total / " + str(len(included)) + "** | 2025–26 | " + " | ".join(str(counts[k]) for k in keys) + " |",
                  "| **2026-only / " + str(recent_n) + "** | sensitivity check | " + " | ".join(str(recent_counts[k]) for k in keys) + " |", "",
                  "Abbreviations: HPP High Poly Project; MIC Mesh Improvement Compilation; BCS standalone Book Covers Skyrim family; Ars Ars Metallica; CCOR Complete Crafting Overhaul Remastered; CRD Crafting Recipe Distributor; AQF Animation Queue Fix; CH Convenient Horses; SH Simplest Horses; IH Immersive Horses; AHL A Horse's Life; LOTD Legacy of the Dragonborn (bundled book-cover provider).", "",
                  "## Excluded from denominator", "", "| Export | Date | Reason |", "|---|---|---|"])
    for item, reason in excluded:
        lines.append(f"| [{item.get('name', item['slug'])}]({item.get('page', item['url'])}) | {(item.get('updated') or 'unknown')[:10]} | {reason} |")
    providers = [item for item in included if main_mods(item)["BCS"] or main_mods(item)["LOTD"]]
    recent_providers = [item for item in providers if item["updated"][:4] == "2026"]
    lines.extend(["", "## Book-cover provider correction", "",
                  f"Recognized BCS-or-LOTD routes (union, not double-counted): **{len(providers)}/{len(included)}**, or **{len(recent_providers)}/{recent_n}** in the 2026-only subset. This is stronger coverage evidence than the standalone BCS column, but still does not prove which textures win in each build.", "",
                  "[LOTD's official incorporated-mods article](https://www.nexusmods.com/skyrimspecialedition/articles/1494) includes BCS and Lost Library. [SkyPatched Missing Books](https://www.nexusmods.com/skyrimspecialedition/mods/149814) explicitly says its edits are already included by LOTD and the mods are incompatible. Do not add a duplicate BCS/SkyPatched stack to a LOTD list merely because it has no standalone BCS folder.", ""])
    lines.extend(["", "## Exact counted main-folder evidence", "",
                  "These are modlist.txt line numbers at retrieval, not page line numbers. Hashes identify normalized UTF-8 joined lines without a trailing newline. Raw exports are not stored in the repository; the script's ignored JSON output retains compact candidate rows, plugin corroboration, metadata and hashes.", ""])
    for item in included:
        found = main_mods(item)
        inventory = next(f for f in item["files"] if f["file"] == "modlist.txt")
        uploader = (item.get("author") or {}).get("name") or "not supplied"
        lines.extend([f"### {item['name']}", "", f"[Public API]({item['url']}); uploader: {uploader}; modlist SHA-256 `{inventory['sha256_joined_lines']}`.", ""])
        for key in keys:
            for row in found[key]:
                lines.append(f"- {key}, line {row['line']}: `{row['text']}`")
        lines.append("")
    lines.extend(["## Exact recognition aliases", ""])
    for key, aliases in MAIN_NAMES.items():
        lines.append(f"- {key}: " + "; ".join(f"`{name}`" for name in sorted(aliases)))
    lines.extend(["", "## Reproduction", "", "```powershell",
                  "python -B -m unittest discover -s audit -p test_survey_requested_slots.py",
                  "python -B audit/survey_requested_slots.py --output records-work/requested-slots-survey.json --markdown records-work/requested-slots-census.md",
                  "```", "", "Re-fetching may change results as the upstream exports change. Re-review unmatched/renamed main mods before comparing future counts. No installation or curator mutation is performed.", ""])
    return "\n".join(lines)


def match_rows(files: list[dict]) -> tuple[list[dict], list[dict]]:
    """Preserve MO2 state, line numbers, and filenames, not guessed adoption."""
    hits, inventories = [], []
    for entry in files:
        name = entry.get("clean_name", entry.get("name", ""))
        if name not in {"modlist.txt", "plugins.txt", "loadorder.txt"}:
            continue
        content = entry.get("content", [])
        rows = content.splitlines() if isinstance(content, str) else content
        if not isinstance(rows, list) or any(not isinstance(row, str) for row in rows):
            raise ValueError(f"Invalid text rows in {name}")
        inventories.append({"file": name, "lines": len(rows),
                            "sha256_joined_lines": hashlib.sha256("\n".join(rows).encode()).hexdigest()})
        for number, line in enumerate(rows, 1):
            stripped = line.strip()
            if not stripped or stripped.startswith("#") or stripped.endswith("_separator"):
                continue
            if name == "modlist.txt":
                state = {"+": "enabled", "-": "disabled", "*": "unmanaged"}.get(stripped[0], "unknown")
            elif name == "plugins.txt":
                state = "enabled" if stripped.startswith("*") else "unmarked"
            else:
                state = "ordered-not-proof-enabled"
            families = [family for family, pattern in PATTERNS.items() if re.search(pattern, stripped, re.I)]
            if families:
                hits.append({"file": name, "line": number, "state": state,
                             "families": families, "text": line})
    return hits, inventories


def fetch(slug: str) -> dict:
    url = f"https://api.loadorderlibrary.com/v1/lists/{slug}"
    request = urllib.request.Request(url, headers={"User-Agent": "SkyrimModAssistant/research-1.0"})
    try:
        with urllib.request.urlopen(request, timeout=25) as response:
            raw = response.read(8_000_001)
        if len(raw) > 8_000_000:
            raise ValueError("Export exceeds 8 MB research cap")
        data = json.loads(raw)["data"]
        matches, inventory = match_rows(data["files"])
        return {"slug": slug, "url": url, "page": f"https://loadorderlibrary.com/lists/{slug}",
                "name": data["name"], "version": data.get("version"), "updated": data.get("updated"),
                "author": data.get("author"), "website": data.get("website"), "readme": data.get("readme"),
                "response_sha256": hashlib.sha256(raw).hexdigest(), "files": inventory, "matches": matches}
    except Exception as exc:
        return {"slug": slug, "url": url, "error": f"{type(exc).__name__}: {exc}"}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True, help="Compact generated research evidence JSON (not mod payloads)")
    parser.add_argument("--slugs", nargs="+", default=list(SLUGS))
    parser.add_argument("--markdown", type=Path, help="Generated citation/accepted-row report")
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()
    with ThreadPoolExecutor(max_workers=4) as pool:
        results = list(pool.map(fetch, dict.fromkeys(args.slugs)))
    document = {"retrieved_utc": datetime.now(timezone.utc).isoformat(),
                "method": "MO2 folder-name candidates plus separate plugin evidence; manual main/patch review required. No absent-mod inference from fetch failures.",
                "patterns": PATTERNS, "exports": results}
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(document, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    if args.markdown:
        args.markdown.parent.mkdir(parents=True, exist_ok=True)
        args.markdown.write_text(census_markdown(document), encoding="utf-8")
    for result in results:
        if "error" in result:
            print(result["slug"], result["error"])
        else:
            matched = [row["text"] for row in result["matches"] if row["file"] == "modlist.txt"] if args.verbose else [key for key, rows in main_mods(result).items() if rows]
            print(result["slug"], result["version"], result["updated"], json.dumps(matched, ensure_ascii=False))


if __name__ == "__main__":
    main()
