<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>true</WarningsAsErrors>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
</Project>
