using System.Text.Json;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Cache;
using Mutagen.Bethesda.Plugins.Order;
using Mutagen.Bethesda.Plugins.Records;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Strings;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Synthesis.Pipeline;

namespace WeaponBalancePatcher;

public static class Program
{
    public const string OutputPlugin = "WeaponBalancePatch.esp";
    public const float SpeedTolerance = 0.00001f;
    public static readonly FormKey SteelMaterialKeyword = FormKey.Factory("01E719:Skyrim.esm");
    public static readonly FormKey MagicDisallowEnchanting = FormKey.Factory("0C27BD:Skyrim.esm");
    public static readonly FormKey BothHandsEquipType = FormKey.Factory("013F45:Skyrim.esm");
    public static readonly FormKey GreatswordTypeKeyword = FormKey.Factory("06D931:Skyrim.esm");

    public static readonly IReadOnlyDictionary<FormKey, WeaponBalanceClass> StandardKeywords =
        new Dictionary<FormKey, WeaponBalanceClass>
        {
            [FormKey.Factory("01E713:Skyrim.esm")] = WeaponBalanceClass.Dagger,
            [FormKey.Factory("01E711:Skyrim.esm")] = WeaponBalanceClass.Sword,
            [FormKey.Factory("01E712:Skyrim.esm")] = WeaponBalanceClass.WarAxe,
            [FormKey.Factory("01E714:Skyrim.esm")] = WeaponBalanceClass.Mace,
            [GreatswordTypeKeyword] = WeaponBalanceClass.Greatsword,
            [FormKey.Factory("06D932:Skyrim.esm")] = WeaponBalanceClass.Battleaxe,
            [FormKey.Factory("06D930:Skyrim.esm")] = WeaponBalanceClass.Warhammer,
        };

    private static Lazy<Settings> _settings = null!;

    public static async Task<int> Main(string[] args)
    {
        ConfigureLocalizationSemantics();
        return await RunGuarded(() => RunCore(args));
    }

    private static async Task<int> RunCore(string[] args)
    {
        if (args.SequenceEqual(["self-test"], StringComparer.OrdinalIgnoreCase))
        {
            return RunSelfTest();
        }

        if (args is ["audit-build", var dataFolder, var loadOrderFile, var pluginPath,
            var settingsPath, var reportPath, var outputPath])
        {
            return BuildAudit.Run(dataFolder, loadOrderFile, pluginPath, settingsPath, reportPath, outputPath);
        }

        if (args is ["audit-final-winners", var finalDataFolder, var finalLoadOrderFile,
            var finalSettingsPath, var finalReportPath, var finalOutputPath])
        {
            return BuildAudit.RunFinalWinners(
                finalDataFolder,
                finalLoadOrderFile,
                finalSettingsPath,
                finalReportPath,
                finalOutputPath);
        }

        return await SynthesisPipeline.Instance
            .SetAutogeneratedSettings("Settings", "settings.json", out _settings)
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch, new PatcherPreferences
            {
                ExclusionMods = [ModKey.FromNameAndExtension(OutputPlugin)],
                // Synthesis 0.36.5 always uses Mutagen's parallel writer and does
                // not expose its ParallelWriteParameters.  Parallel localized
                // writes assign string IDs in thread-arrival order, so otherwise
                // identical runs are not byte-for-byte reproducible.  NoPatch
                // suppresses that built-in writer; RunPatch creates and writes
                // the output itself with the supported SingleThread builder API.
                NoPatch = true,
            })
            .SetTypicalOpen(
                GameRelease.SkyrimSE,
                OutputPlugin,
                new TypicalOpenExtraParameters
                {
                    TargetLanguage = Language.English,
                    Localize = true,
                })
            .Run(args);
    }

    public static async Task<int> RunGuarded(
        Func<Task<int>> operation,
        TextWriter? errorWriter = null)
    {
        try
        {
            return await operation();
        }
        catch (Exception exception)
        {
            var writer = errorWriter ?? Console.Error;
            writer.WriteLine($"ERROR: {exception.GetType().Name}: {exception.Message}");
            return 1;
        }
    }

    private static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        var settings = _settings.Value;
        var profile = settings.ToProfile();
        profile.Validate();
        var rules = Policy.ParseRecordRules(settings.RecordRules);

        // PatcherStateFactory intentionally supplies a null PatchMod when
        // PatcherPreferences.NoPatch is enabled.  Keep ownership of this output
        // explicit instead of relying on that unavailable state property.
        var patchMod = new SkyrimMod(
            ModKey.FromNameAndExtension(OutputPlugin),
            SkyrimRelease.SkyrimSE);

        // Every WEAP override is a full winning record, not a partial field delta.
        // A non-localized output would therefore replace translated FULL/DESC data
        // with only the selected target language.  Force a localized output so
        // Mutagen writes every available source translation to sidecar tables.
        patchMod.UsingLocalization = true;
        patchMod.ModHeader.Author = "Ensrick";
        patchMod.ModHeader.Description =
            "Generated speed-only weapon balance patch. Regenerate from the current winning load order.";
        patchMod.ModHeader.Flags |= SkyrimModHeader.HeaderFlag.Small;

        var rows = new List<SelectionReportRow>();
        var reviewCandidates = new List<ReviewCandidate>();
        var resolvedRules = new HashSet<FormKey>();
        var directSpeedChanged = 0;
        var directSpeedAlreadyTarget = 0;
        var counts = Enum.GetValues<WeaponBalanceClass>()
            .ToDictionary(value => value, _ => new ClassCounts());

        var contexts = state.LoadOrder.PriorityOrder
            .WinningContextOverrides<ISkyrimMod, ISkyrimModGetter, IWeapon, IWeaponGetter>(
                state.LinkCache)
            .OrderBy(context => context.Record.FormKey.ModKey.FileName.String,
                StringComparer.OrdinalIgnoreCase)
            .ThenBy(context => context.Record.FormKey.ID)
            .ToArray();
        var planned = contexts.Select(context => new PlannedWeapon(
            context,
            Policy.Plan(context.Record, context.ModKey, settings, profile, rules)))
            .ToArray();
        var changedSources = planned
            .Where(item => item.Decision.TargetSpeed is { } target &&
                item.Context.Record.Data is { } data &&
                Math.Abs(data.Speed - target) > SpeedTolerance)
            .Select(item => item.Context.Record)
            .ToArray();
        var outputLanguages = LocalizationPolicy.DetermineOutputLanguages(changedSources);
        var providerLocalization = state.LoadOrder.ListedOrder
            .Where(listing => listing.Mod is not null)
            .ToDictionary(listing => listing.ModKey, listing => listing.Mod!.UsingLocalization);

        foreach (var item in planned)
        {
            var context = item.Context;
            var weapon = context.Record;
            var decision = item.Decision;
            if (decision.ExplicitRule)
            {
                resolvedRules.Add(weapon.FormKey);
            }

            var row = SelectionReportRow.From(weapon, context.ModKey, decision);
            rows.Add(row);
            if (decision.WeaponClass is { } classified)
            {
                counts[classified].Classified++;
            }

            if (decision.TargetSpeed is not { } targetSpeed)
            {
                continue;
            }

            if (weapon.Data is null)
            {
                throw new InvalidOperationException(
                    $"{weapon.FormKey} was selected but has no DATA subrecord.");
            }

            if (!decision.ExplicitRule && decision.WeaponClass is { } reviewClass &&
                Policy.NeedsReview(weapon, reviewClass))
            {
                reviewCandidates.Add(CreateReviewCandidate(
                    weapon, context.ModKey, reviewClass, targetSpeed));
            }

            if (Math.Abs(weapon.Data.Speed - targetSpeed) <= SpeedTolerance)
            {
                if (decision.WeaponClass is { } alreadyClass)
                {
                    counts[alreadyClass].AlreadyTarget++;
                }
                else
                {
                    directSpeedAlreadyTarget++;
                }
                continue;
            }

            var patched = patchMod.Weapons.GetOrAddAsOverride(weapon);
            ApplySpeedOnly(patched, targetSpeed);
            Require(providerLocalization.TryGetValue(context.ModKey, out var sourceLocalized),
                $"{weapon.FormKey}: winning provider {context.ModKey} is absent from the load order.");
            LocalizationPolicy.PrepareForLocalizedOutput(
                patched, sourceLocalized, outputLanguages);
            if (decision.WeaponClass is { } changedClass)
            {
                counts[changedClass].Changed++;
            }
            else
            {
                directSpeedChanged++;
            }
        }

        var unresolvedRules = rules.Keys.Except(resolvedRules).OrderBy(key => key.ToString()).ToArray();
        Require(unresolvedRules.Length == 0,
            $"Configured record rules did not resolve in the winning load order: " +
            string.Join(", ", unresolvedRules));

        var outputRows = rows.Where(row => row.Changed)
            .OrderBy(row => row.FormKey, StringComparer.OrdinalIgnoreCase).ToArray();
        var report = new SelectionReport(
            SchemaVersion: 2,
            OutputPlugin,
            Rows: rows.OrderBy(row => row.FormKey, StringComparer.OrdinalIgnoreCase).ToArray(),
            Patched: outputRows,
            ReviewCandidates: reviewCandidates
                .OrderBy(row => row.FormKey, StringComparer.OrdinalIgnoreCase).ToArray(),
            ClassCounts: counts.ToDictionary(pair => pair.Key.ToString(), pair => pair.Value),
            ExplicitRulesConfigured: rules.Count,
            ExplicitRulesResolved: resolvedRules.Count,
            DirectSpeedChanged: directSpeedChanged,
            DirectSpeedAlreadyTarget: directSpeedAlreadyTarget);
        WriteSelectionReport(report);

        WriteDeterministically(patchMod, state.OutputPath.Path, state.LoadOrder);

        Console.WriteLine("Weapon speed normalization summary:");
        foreach (var (weaponClass, classCounts) in counts)
        {
            Console.WriteLine(
                $"  {weaponClass}: classified={classCounts.Classified}, " +
                $"changed={classCounts.Changed}, already_target={classCounts.AlreadyTarget}, " +
                $"target={profile.For(weaponClass):0.####}");
        }
        Console.WriteLine(
            $"Patched {outputRows.Length} WEAP records; explicit rules " +
            $"{resolvedRules.Count}/{rules.Count}; review candidates={reviewCandidates.Count}.");
    }

    public static void ApplySpeedOnly(IWeapon weapon, float targetSpeed)
    {
        Require(float.IsFinite(targetSpeed) && targetSpeed is >= 0.1f and <= 3.0f,
            $"Target speed is outside the defensive range: {targetSpeed}.");
        Require(weapon.Data is not null, $"{weapon.FormKey}: DATA is absent.");
        var data = weapon.Data
            ?? throw new InvalidOperationException($"{weapon.FormKey}: DATA is absent.");
        data.Speed = targetSpeed;
    }

    /// <summary>
    /// Writes a Skyrim plugin deterministically against an explicit load order.
    /// Localized string IDs are allocated serially in record traversal order.
    /// </summary>
    public static void WriteDeterministically(
        ISkyrimModGetter mod,
        string outputPath,
        ILoadOrderGetter<IModListingGetter<ISkyrimModGetter>> loadOrder)
    {
        var fullPath = PrepareOutputPath(mod, outputPath);
        mod.BeginWrite
            .ToPath(fullPath)
            .WithLoadOrder(loadOrder)
            .NoModKeySync()
            .WithTargetLanguage(Language.English)
            .SingleThread()
            .Write();
    }

    private static string PrepareOutputPath(ISkyrimModGetter mod, string outputPath)
    {
        Require(!string.IsNullOrWhiteSpace(outputPath), "Output path is empty.");
        var fullPath = Path.GetFullPath(outputPath);
        Require(string.Equals(
                Path.GetFileName(fullPath),
                mod.ModKey.FileName.String,
                StringComparison.OrdinalIgnoreCase),
            $"Output filename must match {mod.ModKey.FileName.String}: {fullPath}");
        var parent = Path.GetDirectoryName(fullPath)
            ?? throw new InvalidOperationException($"Output path has no parent: {fullPath}");
        Directory.CreateDirectory(parent);
        return fullPath;
    }

    internal static ReviewCandidate CreateReviewCandidate(
        IWeaponGetter weapon,
        ModKey winningProvider,
        WeaponBalanceClass weaponClass,
        float targetSpeed) => new(
            weapon.FormKey.ToString(),
            weapon.EditorID,
            winningProvider.FileName.String,
            weaponClass.ToString(),
            weapon.Data!.Speed,
            targetSpeed,
            (weapon.Keywords ?? []).Any(link => link.FormKey == MagicDisallowEnchanting),
            "Generic record has a non-canonical source speed or MagicDisallowEnchanting; " +
            "review before granting a named exception.");

    private static void WriteSelectionReport(SelectionReport report)
    {
        var path = Environment.GetEnvironmentVariable("WEAPON_BALANCE_REPORT_PATH");
        if (string.IsNullOrWhiteSpace(path))
        {
            Console.WriteLine("WEAPON_BALANCE_REPORT_PATH is unset; selection report not written.");
            return;
        }

        var fullPath = Path.GetFullPath(path);
        Directory.CreateDirectory(Path.GetDirectoryName(fullPath)!);
        File.WriteAllText(fullPath, JsonSerializer.Serialize(report, JsonOptions));
        Console.WriteLine($"Selection report: {fullPath}");
    }

    internal static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        WriteIndented = true,
    };

    public static void ConfigureLocalizationSemantics()
    {
        TranslatedString.DefaultLanguage = Language.English;
        TranslatedString.DefaultLanguageComparisonOnly = false;
    }

    private static int RunSelfTest()
    {
        BalanceRules.Defaults.Validate();
        Require(TranslatedString.DefaultLanguage == Language.English,
            "Localized WEAP comparison target must be English.");
        Require(!TranslatedString.DefaultLanguageComparisonOnly,
            "Only-Speed auditing must compare every available translation.");
        Require(StandardKeywords.Count == 7, "Expected seven standard weapon-type keywords.");
        Require(!StandardKeywords.ContainsKey(SteelMaterialKeyword),
            "WeapMaterialSteel must never be treated as a creature or weapon-type keyword.");
        Require(Math.Abs(BalanceRules.Defaults.Longsword - 1.0f) <= SpeedTolerance,
            "Longsword speed must be 1.0.");
        Console.WriteLine("PASS: profile bounds, seven explicit type keywords, and steel-keyword guard.");
        return 0;
    }

    public static void Require(bool condition, string message)
    {
        if (!condition)
        {
            throw new InvalidOperationException(message);
        }
    }

    private sealed record PlannedWeapon(
        IModContext<ISkyrimMod, ISkyrimModGetter, IWeapon, IWeaponGetter> Context,
        SelectionDecision Decision);
}

public sealed class ClassCounts
{
    public int Classified { get; set; }
    public int Changed { get; set; }
    public int AlreadyTarget { get; set; }
}

public sealed record SelectionReport(
    int SchemaVersion,
    string OutputPlugin,
    IReadOnlyList<SelectionReportRow> Rows,
    IReadOnlyList<SelectionReportRow> Patched,
    IReadOnlyList<ReviewCandidate> ReviewCandidates,
    IReadOnlyDictionary<string, ClassCounts> ClassCounts,
    int ExplicitRulesConfigured,
    int ExplicitRulesResolved,
    int DirectSpeedChanged,
    int DirectSpeedAlreadyTarget);

public sealed record SelectionReportRow(
    string FormKey,
    string? EditorId,
    string WinningProvider,
    string Action,
    string Source,
    string? WeaponClass,
    float? SourceSpeed,
    ushort? SourceDamage,
    float? TargetSpeed,
    bool ExplicitRule,
    string? Reason,
    bool Changed)
{
    public static SelectionReportRow From(
        IWeaponGetter weapon,
        ModKey winningProvider,
        SelectionDecision decision) => new(
            weapon.FormKey.ToString(),
            weapon.EditorID,
            winningProvider.FileName.String,
            decision.Action.ToString(),
            decision.Source,
            decision.WeaponClass?.ToString(),
            weapon.Data?.Speed,
            weapon.BasicStats?.Damage,
            decision.TargetSpeed,
            decision.ExplicitRule,
            decision.Reason,
            decision.TargetSpeed is { } target && weapon.Data is { } data &&
                Math.Abs(data.Speed - target) > Program.SpeedTolerance);
}

public sealed record ReviewCandidate(
    string FormKey,
    string? EditorId,
    string WinningProvider,
    string WeaponClass,
    float SourceSpeed,
    float TargetSpeed,
    bool MagicDisallowEnchanting,
    string Reason);
