using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;

namespace WeaponBalancePatcher;

public static class Program
{
    private const string OutputPlugin = "WeaponBalancePatch.esp";
    private const float SpeedTolerance = 0.00001f;
    private static readonly FormKey CreatureWeaponKeyword = FormKey.Factory("01E719:Skyrim.esm");

    private static readonly IReadOnlyDictionary<FormKey, WeaponBalanceClass> StandardKeywords =
        new Dictionary<FormKey, WeaponBalanceClass>
        {
            [FormKey.Factory("01E713:Skyrim.esm")] = WeaponBalanceClass.Dagger,
            [FormKey.Factory("01E711:Skyrim.esm")] = WeaponBalanceClass.Sword,
            [FormKey.Factory("01E712:Skyrim.esm")] = WeaponBalanceClass.WarAxe,
            [FormKey.Factory("01E714:Skyrim.esm")] = WeaponBalanceClass.Mace,
            [FormKey.Factory("06D931:Skyrim.esm")] = WeaponBalanceClass.Greatsword,
            [FormKey.Factory("06D932:Skyrim.esm")] = WeaponBalanceClass.Battleaxe,
            [FormKey.Factory("06D930:Skyrim.esm")] = WeaponBalanceClass.Warhammer,
        };

    private static Lazy<Settings> _settings = null!;

    public static async Task<int> Main(string[] args)
    {
        if (args.SequenceEqual(["self-test"], StringComparer.OrdinalIgnoreCase))
        {
            return RunSelfTest();
        }

        return await SynthesisPipeline.Instance
            .SetAutogeneratedSettings("Settings", "settings.json", out _settings)
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
            .SetTypicalOpen(GameRelease.SkyrimSE, OutputPlugin)
            .Run(args);
    }

    private static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        var settings = _settings.Value;
        var profile = settings.ToProfile();
        profile.Validate();

        state.PatchMod.ModHeader.Flags |= SkyrimModHeader.HeaderFlag.Small;

        var excludes = ParseFormKeys(settings.Exclude, nameof(settings.Exclude));
        var forced = ParseForcedClasses(settings.ForceClass);
        var changedByClass = Enum.GetValues<WeaponBalanceClass>()
            .ToDictionary(x => x, _ => 0);
        var alreadyTargetByClass = Enum.GetValues<WeaponBalanceClass>()
            .ToDictionary(x => x, _ => 0);
        var ambiguous = new List<string>();
        var missingData = new List<string>();
        var excludedNonPlayable = 0;
        var excludedUtility = 0;

        foreach (var weapon in state.LoadOrder.PriorityOrder.Weapon().WinningOverrides())
        {
            if (excludes.Contains(weapon.FormKey))
            {
                continue;
            }

            if (!settings.IncludeNonPlayableWeapons && IsNonPlayableWeapon(weapon))
            {
                excludedNonPlayable++;
                continue;
            }

            if (IsCreatureOrUtilityWeapon(weapon, settings.ExcludeEditorIdContains))
            {
                excludedUtility++;
                continue;
            }

            var classification = Classify(weapon, forced, settings.UseAnimationFallback);
            if (classification.Ambiguous)
            {
                ambiguous.Add($"{weapon.FormKey} {weapon.EditorID ?? "(no EditorID)"}");
                continue;
            }

            if (classification.WeaponClass is not { } weaponClass)
            {
                continue;
            }

            if (weapon.Data is null)
            {
                missingData.Add($"{weapon.FormKey} {weapon.EditorID ?? "(no EditorID)"}");
                continue;
            }

            var targetSpeed = profile.For(weaponClass);
            if (Math.Abs(weapon.Data.Speed - targetSpeed) <= SpeedTolerance)
            {
                alreadyTargetByClass[weaponClass]++;
                continue;
            }

            var patched = state.PatchMod.Weapons.GetOrAddAsOverride(weapon);
            patched.Data!.Speed = targetSpeed;
            changedByClass[weaponClass]++;
        }

        Console.WriteLine("Weapon speed normalization summary:");
        foreach (var weaponClass in Enum.GetValues<WeaponBalanceClass>())
        {
            Console.WriteLine(
                $"  {weaponClass}: changed={changedByClass[weaponClass]}, " +
                $"already_target={alreadyTargetByClass[weaponClass]}, " +
                $"target={profile.For(weaponClass):0.####}");
        }

        foreach (var item in ambiguous)
        {
            Console.WriteLine($"SKIP ambiguous standard weapon keywords: {item}");
        }

        foreach (var item in missingData)
        {
            Console.WriteLine($"SKIP classified weapon with no DATA subrecord: {item}");
        }

        Console.WriteLine(
            $"Patched {changedByClass.Values.Sum()} records; " +
            $"ambiguous={ambiguous.Count}; missing_data={missingData.Count}; " +
            $"excluded_nonplayable={excludedNonPlayable}; excluded_utility={excludedUtility}.");
    }

    private static bool IsNonPlayableWeapon(IWeaponGetter weapon)
    {
        if ((weapon.MajorFlags & Weapon.MajorFlag.NonPlayable) != 0)
        {
            return true;
        }

        return weapon.Data is { } data &&
            (data.Flags & WeaponData.Flag.NonPlayable) != 0;
    }

    private static bool IsCreatureOrUtilityWeapon(
        IWeaponGetter weapon,
        IEnumerable<string> excludedEditorIdFragments)
    {
        if (weapon.Data is { } data &&
            (data.Flags & WeaponData.Flag.NotUsedInNormalCombat) != 0)
        {
            return true;
        }

        if ((weapon.Keywords ?? []).Any(keyword => keyword.FormKey == CreatureWeaponKeyword))
        {
            return true;
        }

        return weapon.EditorID is { } editorId && (excludedEditorIdFragments ?? [])
            .Where(fragment => !string.IsNullOrWhiteSpace(fragment))
            .Any(fragment => editorId.Contains(fragment.Trim(), StringComparison.OrdinalIgnoreCase));
    }

    public static Classification Classify(
        IWeaponGetter weapon,
        IReadOnlyDictionary<FormKey, WeaponBalanceClass> forced,
        bool useAnimationFallback)
    {
        if (forced.TryGetValue(weapon.FormKey, out var forcedClass))
        {
            return new Classification(forcedClass, false, "forced");
        }

        var keywordClasses = (weapon.Keywords ?? [])
            .Select(x => x.FormKey)
            .Where(StandardKeywords.ContainsKey)
            .Select(x => StandardKeywords[x])
            .Distinct()
            .ToArray();

        if (keywordClasses.Length > 1)
        {
            return new Classification(null, true, "multiple standard weapon keywords");
        }

        if (keywordClasses.Length == 1)
        {
            return new Classification(keywordClasses[0], false, "keyword");
        }

        if (!useAnimationFallback || weapon.Data is null)
        {
            return new Classification(null, false, "unclassified");
        }

        var fallback = weapon.Data.AnimationType switch
        {
            WeaponAnimationType.OneHandDagger => WeaponBalanceClass.Dagger,
            WeaponAnimationType.OneHandSword => WeaponBalanceClass.Sword,
            WeaponAnimationType.OneHandAxe => WeaponBalanceClass.WarAxe,
            WeaponAnimationType.OneHandMace => WeaponBalanceClass.Mace,
            WeaponAnimationType.TwoHandSword => WeaponBalanceClass.Greatsword,
            // Battleaxes and warhammers share TwoHandAxe. Without a keyword,
            // choosing between their intentionally different speeds would be a guess.
            _ => (WeaponBalanceClass?)null,
        };

        return new Classification(fallback, false, fallback is null ? "unclassified" : "animation fallback");
    }

    private static HashSet<FormKey> ParseFormKeys(IEnumerable<string> values, string settingName)
    {
        var result = new HashSet<FormKey>();
        foreach (var value in values)
        {
            try
            {
                result.Add(FormKey.Factory(value.Trim()));
            }
            catch (Exception exception)
            {
                throw new InvalidOperationException(
                    $"Invalid FormID '{value}' in {settingName}: {exception.Message}", exception);
            }
        }

        return result;
    }

    private static Dictionary<FormKey, WeaponBalanceClass> ParseForcedClasses(
        IEnumerable<ForceClassRule> rules)
    {
        var result = new Dictionary<FormKey, WeaponBalanceClass>();
        foreach (var rule in rules)
        {
            FormKey formKey;
            try
            {
                formKey = FormKey.Factory(rule.FormId.Trim());
            }
            catch (Exception exception)
            {
                throw new InvalidOperationException(
                    $"Invalid ForceClass FormID '{rule.FormId}': {exception.Message}", exception);
            }

            if (!BalanceRules.TryParseClass(rule.Class, out var weaponClass))
            {
                throw new InvalidOperationException(
                    $"Invalid ForceClass class '{rule.Class}' for {rule.FormId}.");
            }

            if (!result.TryAdd(formKey, weaponClass))
            {
                throw new InvalidOperationException($"Duplicate ForceClass FormID: {formKey}.");
            }
        }

        return result;
    }

    private static int RunSelfTest()
    {
        BalanceRules.Defaults.Validate();

        var expected = new Dictionary<WeaponBalanceClass, float>
        {
            [WeaponBalanceClass.Dagger] = 1.25f,
            [WeaponBalanceClass.Sword] = 1.0f,
            [WeaponBalanceClass.WarAxe] = 15.0f / 16.0f,
            [WeaponBalanceClass.Mace] = 15.0f / 17.0f,
            [WeaponBalanceClass.Greatsword] = 20.0f / 25.0f,
            [WeaponBalanceClass.Battleaxe] = 20.0f / 26.0f,
            [WeaponBalanceClass.Warhammer] = 20.0f / 28.0f,
        };

        foreach (var (weaponClass, expectedSpeed) in expected)
        {
            var actual = BalanceRules.Defaults.For(weaponClass);
            if (Math.Abs(actual - expectedSpeed) > SpeedTolerance)
            {
                Console.Error.WriteLine(
                    $"FAIL {weaponClass}: expected {expectedSpeed}, got {actual}");
                return 2;
            }
        }

        Console.WriteLine("PASS: seven class targets and profile bounds.");
        return 0;
    }
}

public sealed record Classification(
    WeaponBalanceClass? WeaponClass,
    bool Ambiguous,
    string Source);
